server:
  port: 9527
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
zuul:
  routes:
    user.serviceId: xqg-plat
    user.path: /user/**
  ignored-services: "*" #用*来通配符，忽略从9527端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀